project:
  type: website

format:
  html:
    theme: cosmo        
    toc: true              
    embed-resources: true 
    css: styles.css        

execute:
  echo: true
  eval: true
  code-fold: true

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research_introduction.qmd
        text: "Research"
      - href: data_analysis.ipynb
        text: "Data Analysis"
      - href: career_plan.qmd
        text: "Career Strategy"
      - text: "Plots"
        href: plots.qmd
