project:
  type: website

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research_introduction.qmd
        text: "Research"
      - href: data_analysis.ipynb
        text: "Data Analysis"
      - href: career_plan.qmd
        text: "Career Strategy"

-----------------------------------------------

project:
  type: website

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css

execute:
  echo: true
  eval: false  # Disable code execution on GitHub Pages
  code-fold: true

format:
  html:
    embed-resources: true 

website:
  title: "Data Analysis Report"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Plots"
        href: plots.qmd
