project:
  type: website
  output-dir: _site

format:
  html:
    theme: cosmo        
    toc: true              
    embed-resources: true 
    css: styles.css        

execute:
  echo: true
  eval: true
  code-fold: true

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research_introduction.qmd
        text: "Introduction"
      - href: career_plan.qmd
        text: "Career Strategy"
      - href: data_cleaning.ipynb
        text: "Data Cleaning & Exploration"
      - href: eda.ipynb
        text: "Exploratory Data Analysis"
      - href: skills_gap_analysis.ipynb
        text: "Skill Gap Analysis"
      - href: ml_methods.ipynb
        text: "ML Methods"
      - href: nlp_methods.ipynb
        text: "NLP Methods"

metadata-files: ["_metadata.yml"]