project:
  type: website
  output-dir: _site
  render:
  - "*.qmd"
  - "*.ipynb"
  - "!working_files/individual_analysis_folder/*"
  - "!working_files/individual_analysis_folder/**/*"

format:
  html:
    theme: cosmo        
    toc: true              
    embed-resources: true 
    css: styles.css        

execute:
  echo: true
  eval: true
  code-fold: true

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research_introduction.qmd
        text: "Introduction"
      - href: career_plan.qmd
        text: "Career Strategy"
      - href: data_cleaning.ipynb
        text: "Data Cleaning & Exploration"
      - href: eda.ipynb
        text: "Exploratory Data Analysis"
      - href: skills_gap_analysis.ipynb
        text: "Skill Gap Analysis"
      - href: career_plan.qmd
        text: "Career Strategy"  
      - href: ml_supervised.ipynb
        text: "ML Supervised Method"
      - href: ml_unsupervised.ipynb
        text: "ML Unsupervised Method"

metadata-files: ["_metadata.yml"]